In [5]:
import pandas as pd
DF=pd.read_csv("data/Bitcoin_hist.csv")

In [6]:
shape = DF.shape
shape

(365, 9)

In [ ]:
ftr = DF.head(3)
ftr

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,Bitcoin,BTC,"Feb 26, 2022","$39,213.08","$40,005.35","$38,702.53","$39,105.15","$17,467,554,129","$741,789,694,059"
1,Bitcoin,BTC,"Feb 25, 2022","$38,333.75","$39,630.32","$38,111.34","$39,214.22","$26,545,599,159","$743,827,806,938"
2,Bitcoin,BTC,"Feb 24, 2022","$37,278.57","$38,968.84","$34,459.22","$38,332.61","$46,383,802,093","$727,072,550,320"

In [8]:
most = DF.describe()
most

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
count,365,365,365,365,365,365,365,365,365
unique,1,1,365,365,365,365,365,365,365
top,Bitcoin,BTC,"Feb 26, 2022","$39,213.08","$40,005.35","$38,702.53","$39,105.15","$17,467,554,129","$741,789,694,059"
freq,365,365,1,1,1,1,1,1,1

In [9]:
nullcheck = DF.notna()
nullcheck

,currency,ticker,date,open_price,high,low,close_price,volume,market_cap
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
360,True,True,True,True,True,True,True,True,True
361,True,True,True,True,True,True,True,True,True
362,True,True,True,True,True,True,True,True,True
363,True,True,True,True,True,True,True,True,True
364,True,True,True,True,True,True,True,True,True